notes/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('notes.views',
    (r'^$', 'index'),
    (r'^c/$', 'company_index'),
    (r'^p/$', 'position_index'),
    (r'^c/(?P<company_id>\d+)/$', 'company'),
    (r'^c/(?P<company_name>.+)/$', 'company_by_name'),
    (r'^p/(?P<position_id>\d+)/$', 'position'),
    (r'^p/(?P<position_title>.+)/$', 'position_by_title'),
    (r'^i/$', 'interviews'),
    (r'^edit/(?P<id>\d+)/$', 'edit_interview'),
    (r'^editquestion/(?P<id>\d+)/$', 'edit_question'),
    (r'^companytags/$', 'companytags'),
    (r'^positiontags/$', 'positiontags'),
    (r'^add/$', 'add'),

    (r'^signup/$', 'signup'),

    ##### 

)

urls.py
import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^notes/', include('notes.urls')),

    (r'^notes/login/', 'django.contrib.auth.views.login'),
    (r'^notes/logout/', 'django.contrib.auth.views.logout'),
    (r'^notes/password_change/', 'django.contrib.auth.views.password_change'),
    (r'^notes/password_change_done/', 'django.contrib.auth.views.password_change'),

    # TODO config web server to do this
    (r'^notes/static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    (r'^notes/admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^notes/admin/', include(admin.site.urls)),
)

notes/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.ForeignKey(User, unique=True)

    def __unicode__(self):
        return self.user.username

class Position(models.Model):
    title = models.CharField(max_length=50, unique=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=True)

    def __unicode__(self):
        return self.title

class Company(models.Model):
    name = models.CharField(max_length=50, unique=True)
    positions = models.ManyToManyField(Position)
    updated = models.DateTimeField(auto_now=True, auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Companies'

class Interview(models.Model):
    company = models.ForeignKey(Company)
    position = models.ForeignKey(Position)
    profile = models.ForeignKey(Profile, blank=True, null=True)
    description = models.CharField(max_length=2000)
    date = models.IntegerField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=True)

    def __unicode__(self):
        return '%s interview at %s' % (self.position.title, self.company.name)

class Question(models.Model):
    interview = models.ForeignKey(Interview)
    question = models.CharField(max_length=2000)
    answer = models.CharField(max_length=2000, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=True)

    def __unicode__(self):
        return 'Question for %s' % (self.interview)

notes/forms.py
from django import forms
from django.contrib.flatpages.models import FlatPage
from django.forms import Textarea
from notes.models import Interview
from notes.models import Question

class InterviewForm(forms.Form):
    company = forms.CharField(max_length=50, \
        widget=forms.TextInput(attrs={'size':50}))
    position = forms.CharField(max_length=50, \
        widget=forms.TextInput(attrs={'size':50}))
    date = forms.DateField(label='Date of interview')
    description = forms.CharField(max_length=2000, \
        widget=forms.widgets.Textarea(attrs={'rows':6,'cols':80}))

    question = forms.CharField(max_length=2000, \
        widget=forms.widgets.Textarea(attrs={'rows':6,'cols':80}))
    answer = forms.CharField(max_length=2000, required=False, \
        widget=forms.widgets.Textarea(attrs={'rows':6,'cols':80}))

    def clean(self):
        for k in self.cleaned_data:
            if k.startswith('id_question'):
                # allow questions with no answers
                answer = k.replace('question', 'answer')
                if not answer in self.cleaned_data:
                    self.cleaned_data[answer] = ''
            elif k.startswith('id_answer'):
                # prevent answers with no questions
                question = k.replace('answer', 'question')
                if not question in self.cleaned_data or \
                    self.cleaned_data[question].strip() == '':
                    raise forms.ValidationError('Provided answer without a question')
        return self.cleaned_data

    class Meta:
        fields = ('company', 'position', 'date', 'description', 'question', 'answer')

class InterviewEditForm(forms.ModelForm):
    description = forms.CharField(max_length=2000, \
        widget=forms.widgets.Textarea(attrs={'rows':6,'cols':80}))

    class Meta:
        model = Interview
        fields = ('description',)

class QuestionEditForm(forms.ModelForm):
    question = forms.CharField(max_length=2000, \
        widget=forms.widgets.Textarea(attrs={'rows':6,'cols':80}))
    answer = forms.CharField(max_length=2000, required=False, \
        widget=forms.widgets.Textarea(attrs={'rows':6,'cols':80}))

    class Meta:
        model = Question
        fields = ('question', 'answer',)

notes/views.py
import json

from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.shortcuts import render_to_response, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect

from django.core.exceptions import ObjectDoesNotExist

from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.forms.formsets import formset_factory
from django.template import RequestContext

from notes.forms import InterviewForm
from notes.forms import InterviewEditForm
from notes.forms import QuestionEditForm
from notes.models import Profile
from notes.models import Company
from notes.models import Position
from notes.models import Interview
from notes.models import Question

# Lists top N companies and positions, by things like quantity and 
# recent activity
def index(request):
    return render_to_response('notes/home.html', \
        {
            'companies': Company.objects.all().order_by('-updated')[:10],
        }, context_instance=RequestContext(request))

def search(request):
    return render_to_response('notes/search.html', \
        {
        }, context_instance=RequestContext(request))

# Lists by company and top N positions
def company_index(request):
    order = request.GET.get('order', 'name')
    
    if order == 'name':
        companies = Company.objects.all().order_by('name')
    elif order == 'positions':
        # Sort by # positions
        companies = Company.objects.all().annotate( \
            poscount=Count('positions')).order_by('-poscount')
    elif order == 'interviews':
        # Sort by # interviews
        companies = Company.objects.all().annotate( \
            icount=Count('interview')).order_by('-icount')
    else:
        # order by recent
        companies = Company.objects.all().order_by('-updated')

    return render_to_response('notes/company_index.html', \
        {
            'order': order,
            'companies': companies,
        }, context_instance=RequestContext(request))

# Lists by position and top N companies
def position_index(request):
    order = request.GET.get('order', 'title')
    
    if order == 'title':
        positions = Position.objects.all().order_by('title')
    elif order == 'companies':
        # Sort by # companies
        positions = Position.objects.all().annotate( \
            ccount=Count('company')).order_by('-ccount')
    elif order == 'interviews':
        # Sort by # interviews
        positions = Position.objects.all().annotate( \
            icount=Count('interview')).order_by('-icount')
    else:
        # order by recent
        positions = Position.objects.all().order_by('-updated')

    return render_to_response('notes/position_index.html', \
        {
            'order': order,
            'positions': positions,
        }, context_instance=RequestContext(request))

# positions by company
def company(request, company_id):
    company = Company.objects.get(pk=company_id)
    return render_to_response('notes/company.html', \
        {
            'company': company,
        }, context_instance=RequestContext(request))

def company_by_name(request, company_name):
    try:
        company = Company.objects.get(name=company_name)
    except ObjectDoesNotExist:
        try:
            company = Company.objects.get(name__contains=company_name)
        except ObjectDoesNotExist:
            return -1

    if id < 0:
        raise Http404
    return company(request, company.id)

# companies by position
def position(request, position_id):
    position = Position.objects.get(pk=position_id)
    return render_to_response('notes/position.html', \
        {
            'position': position,
        }, context_instance=RequestContext(request))

def position_by_title(request, position_title):
    try:
        position = Position.objects.get(title=position_title)
    except ObjectDoesNotExist:
        try:
            position = Company.objects.get(name__contains=position_title)
        except ObjectDoesNotExist:
            return -1

    if id < 0:
        raise Http404
    return position(request, position.id)

# Lists by position, company, or both, by id
def interviews(request):
    args = request.GET
    kwargs = {}
    if 'company' in args:
        kwargs['company__id'] = args['company']
    if 'position' in args:
        kwargs['position__id'] = args['position']

    if len(kwargs) < 1:
        raise Http404

    interviews = Interview.objects.filter(**kwargs).order_by('-position', 'date')
    if len(interviews) < 1:
        raise Http404

    return render_to_response('notes/interviews.html', \
        {
            'interviews': interviews,
            'loggedin': not request.user.is_anonymous(),
            # TODO logged in users get error here if there is no profile for them (ie. admin).
            'profile': None if request.user.is_anonymous() else request.user.get_profile(),
        }, context_instance=RequestContext(request))

# Submit interview
def add(request):
    failed = False
    addednew = False
    formerror = None

    if request.POST:
        custom_fields = [f for f in request.POST \
            if f.startswith('id_answer') or f.startswith('id_question')]

        attrs = dict((field, forms.CharField(max_length=100, required=False)) \
            for field in custom_fields)
        DynamicForm = type("DynamicForm", (InterviewForm,), attrs)

        f = DynamicForm(request.POST)
        # blank description can be valid w/ question and answer
        if f.is_valid():
            d = f.cleaned_data

            input_company = d['company']
            input_position = d['position']

            input_date = d.get('date', None)
            input_description = d.get('description', None)
            input_question = d.get('question', None)
            input_answer = d.get('answer', '')

            # find position
            try:
                position = Position.objects.get(title=input_position)
            except ObjectDoesNotExist:
                position = Position()
                position.title = input_position
                position.save()

            # find company
            try:
                company = Company.objects.get(name=input_company)
            except ObjectDoesNotExist:
                company = Company()
                company.name = input_company
                company.save()
                company.positions.add(position)
                company.save()

            position.company_set.add(company)
            position.save()
                
            i = Interview()
            # add profile if logged in
            i.profile = None if request.user.is_anonymous() else request.user.get_profile()
            # other interview details
            i.company = company
            i.position = position
            i.description = input_description
            i.date = input_date
            i.save()

            # questions
            if input_question:
                def saveQandA(interview, question, answer):
                    addme = Question()
                    addme.interview = interview;
                    addme.question = question
                    addme.answer = answer
                    addme.save()

                saveQandA(i, input_question, input_answer)
                c = 2
                while 1:
                    q = 'id_question'+str(c)
                    a = 'id_answer'+str(c)
                    if q in d:
                        saveQandA(i, d[q], d.get(a, ''))
                        c += 1
                    else:
                        break

            addednew = True
        else:
            formerror = f.errors
            failed = True

    return render_to_response('notes/add.html', \
        {
            'form': InterviewForm(),
            'addednew': addednew,
            'failed': failed,
            'formerror': formerror,
            'loggedin': not request.user.is_anonymous(),
        }, context_instance=RequestContext(request))

# Edit interview
@login_required
def edit_interview(request, id):
    interview = get_object_or_404(Interview, pk=id)
    if request.user.get_profile() != interview.profile:
        # no good
        return HttpResponse("Not your interview - maybe you need to login or change accounts.")

    formerror = None
    success = False

    if request.POST:
        f = InterviewEditForm(request.POST, instance=interview)
        if f.is_valid():
            f.save()
            success = True
        else:
            formerror = f.errors
            success = False

    return render_to_response('notes/edit.html', \
        {
            'form': InterviewEditForm(instance=interview),
            'interview': interview,
            'formerror': formerror,
            'success': success,
        }, context_instance=RequestContext(request))

# Edit question
@login_required
def edit_question(request, id):
    question = get_object_or_404(Question, pk=id)
    if request.user.get_profile() != question.interview.profile:
        return HttpResponse("Not your question- maybe you need to login or change accounts.")

    question = get_object_or_404(Question, pk=id)
    if request.user.get_profile() != question.interview.profile:
        # no good
        return HttpResponse("Not your interview - maybe you need to login or change accounts.")

    formerror = None
    success = False

    if request.POST:
        f = QuestionEditForm(request.POST, instance=question)
        if f.is_valid():
            f.save()
            success = True
        else:
            formerror = f.errors
            success = False

    return render_to_response('notes/edit_question.html', \
        {
            'form': QuestionEditForm(instance=question),
            'question': question,
            'formerror': formerror,
            'success': success,
        }, context_instance=RequestContext(request))

# Typeahead completion for entering a company name

templates/notes/add.html
{% extends "base.html" %}
{%block title%}add{%endblock%}
{%block head%}

{{form.media}}

<link rel="stylesheet" href="/notes/static/css/uniform.default.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="/notes/static/css/jquery-ui-1.8.7.custom.css" type="text/css" media="screen" charset="utf-8" />

<script src="/notes/static/js/jquery.uniform.min.js" type="text/javascript"></script>
<script src="/notes/static/js/jquery-ui-1.8.7.custom.min.js" type="text/javascript"></script>
<script src="/notes/static/js/autoresize.jquery.min.js" type="text/javascript"></script>

<style>
    .ui-autocomplete {
        max-height: 100px;
        overflow-y: auto;
        overflow-x: hidden;
        padding-right: 20px;
    }
    * html .ui-autocomplete {
        height: 100px;
    }
</style>

<script type="text/javascript">
      $(function(){
        $('input, textarea, select, button').uniform();
      /*
        $('#id_date').datepicker({
            changeMonth: true,
            changeYear: true,
            maxDate: '+0D',
            onChangeMonthYear: function(y, m, inst) {
                $('#id_date').datepicker('setDate', m+'/1'+'/'+y);
            }
        });
      */

        $('#id_date').val('{% now "Y" %}');
      });


      var c = 2;
      var origheight;
      $(document).ready(function() {
        origheight = $('#qAndA_base textarea:first').height();

        $('#id_date').datepicker('setDate', 'c');

        //dynamic fields
        $('#add_field').click(function() {
            var d = $('#qAndA_base').clone(true);
            d.attr('class', 'qAndA');

            var q = d.find('textarea:first').next();
            var a = d.find('textarea:last');

            q.attr('id', 'id_question'+c);
            q.attr('name', 'id_question'+c);
            q.height(origheight);
            a.attr('id', 'id_answer'+c);
            a.attr('name', 'id_answer'+c);
            a.height(origheight);

            d.insertAfter($('.qAndA:last'));
            c++;
            return false;
        });

        // autoresize
        $('textarea').autoResize({
            onResize : function() {
                $(this).css({opacity:0.8});
            },
            animateCallback : function() {
                $(this).css({opacity:1});
            },
            animateDuration : 300,
            extraSpace : 40
        });

        // autocompletes
        var cacheC = {}, lastXhrC; 
        $("#id_company").autocomplete({
            minLength: 2,
            source: function(request, response) {
                var term = request.term;
                if (term in cacheC) {
                    response(cacheC[term]);
                    return;
                }
                lastXhrC = $.getJSON('/notes/companytags/', request, function(data, status, xhr) {
                    cacheC[term] = data;
                    if (xhr === lastXhrC) {
                        response(data);
                    }
                });
            }
        }); 
        var cacheP = {}, lastXhrP; 
        $("#id_position").autocomplete({
            minLength: 2,
            source: function(request, response) {
                var term = request.term;
                if (term in cacheP) {
                    response(cacheP[term]);
                    return;
                }
                lastXhrP = $.getJSON('/notes/positiontags/', request, function(data, status, xhr) {
                    cacheP[term] = data;
                    if (xhr === lastXhrP) {
                        response(data);
                    }
                });
            }
        }); 
      });
</script>
{%endblock head%}

{%block header%}
Add an interview experience
{%endblock header%}
{%block content%}
{%if addednew%}
    <strong>Your submission was received and will be up shortly.  Thanks!</strong>
{%else%}
    {%if failed%}
        <strong>Something was wrong with your submission:</strong><br>
        {{formerror}}
    {%endif%}
{%endif%}

{%if not loggedin%}
<a href="/notes/login">Login</a> so you can edit this in the future.
{%endif%}
<form id="submitform" action="/notes/add/" method="POST">
<p><strong>Company</strong>: {{form.company}}</p>
<p><strong>Position</strong>: {{form.position}}</p>
<p><strong>Year of interview</strong>: {{form.date}} </p>
<p><strong>Description of your experience</strong>:<br>
(interviewer expectations, things that would've been helpful to know, ways to prepare, etc.)<br>{{form.description}}</p>

<div class="indent">
<div id="qAndA_base" class="qAndA">
<p>Question:<br>{{form.question}}</p>
<p>Answer (if applicable):<br>{{form.answer}}</p>
</div>
<div id="add_field"><strong>[+] <a href="#">Add another question</strong></a></div>
</div>
<br>
<input id="submit" type="submit" value="Done"/>
{%endblock content%}

templates/notes/company.html
{% extends "base.html" %}
{% load notes_extras %}

{%block title%}{{company.name}}{%endblock%}
{%block header%}{{company.name}}{%endblock%}
{%block content%}

<p>
<h2>Positions</h2>
<ul>
{%for position in company.positions.all%}
    <!-- TODO filter interview_set by company -->
    <li><a href="/notes/i/?company={{company.id}}&position={{position.id}}">{{position.title}}</a> - ({{ position.interview_set|interviews_per_company_position:company }} interviews)
{%endfor%}
</ul>
</p>

<p>
<h2>Interviews</h2>
<ul>
{%for interview in company.interview_set.all%}
    <li>{{interview.description|truncatewords:10}}... - ({{interview.position.title}}) - {{interview.question_set.all.count}} questions - <a href="/notes/i/?company={{company.id}}">MORE</a></li>
{%endfor%}
</ul>
</p>

{%endblock content%}

templates/notes/company_index.html
{% extends "base.html" %}
{%load notes_extras%}

{%block title%}company index{%endblock%}
{%block header%}Companies{%endblock%}
{%block content%}
Order by:
{%ifnotequal order "name"%}<a href="?order=name">{%endifnotequal%}
name
{%ifnotequal order "name"%}</a>{%endifnotequal%}
-
{%ifnotequal order "positions"%}<a href="?order=positions">{%endifnotequal%}
#positions
{%ifnotequal order "positions"%}</a>{%endifnotequal%}
-
{%ifnotequal order "interviews"%}<a href="?order=interviews">{%endifnotequal%}
#interviews
{%ifnotequal order "interviews"%}</a>{%endifnotequal%}
-
{%ifnotequal order "recent"%}<a href="?order=recent">{%endifnotequal%}
recent
{%ifnotequal order "recent"%}</a>{%endifnotequal%}

<ul>
{%for company in companies%}
    <li><a href="/notes/c/{{company.id}}">{{company.name}}</a> - ({{company.positions.all.count}} positions, {{company.interview_set.all.count}} interviews) - updated {{company|format_updated}}</li>
{%empty%}
    None
{%endfor%}
</ul>
{%endblock content%}

templates/notes/edit.html
{% extends "base.html" %}
{%block title%}edit{%endblock%}

{%block header%}Edit interview{%endblock%}

{%block content%}
{%if errors%}
<strong>{{errors}}</strong>
{%endif%}
{%if success%}
<strong>Changes saved successfully</strong>
{%endif%}
<form id="editform" action="" method="POST">
{{form.as_p}}
<input id="submit" type="submit" value="Save"/>
</form>

<hr/>

{%for q in interview.question_set.all%}
    <p>
    <a href="/notes/editquestion/{{q.id}}">[edit]</a> <strong>{{q.question}}</strong>: {{q.answer}}
    </p>
{%endfor%}
{%endblock content%}

templates/notes/edit_question.html
{% extends "base.html" %}
{%block title%}edit{%endblock%}

{%block header%}Edit question{%endblock%}

{%block content%}
{%if errors%}
<strong>{{errors}}</strong>
{%endif%}
{%if success%}
<strong>Changes saved successfully</strong>
{%endif%}
<form action="" method="post">
{{form.as_p}}
<input type="submit" value="Save">
</form>
{%endblock content%}

templates/notes/home.html
{%extends "base.html"%}
{%load notes_extras%}

{%block title%}home{%endblock%}

{%block header%}Home{%endblock%}
{%block content%}
<p>
This site is a repository for job search experiences and advice for Dartmouth students (specifically, Dartmouth CS students).
</p>
<p>
Recently updated companies:
<ul>
{%for company in companies%}
    <li><a href="/notes/c/{{company.id}}">{{company.name}}</a> - ({{company.positions.all.count}} positions, {{company.interview_set.all.count}} interviews) - updated {{company|format_updated}}</li>
{%empty%}
    None
{%endfor%}
</ul>
</p>
{%endblock content%}

templates/notes/interviews.html
{% extends "base.html" %}
{%block title%}interviews{%endblock%}
{%block header%}Interviews{%endblock%}
{%block content%}

{%ifequal interiews.count 0%}
    No such interviews exist.
{%endifequal%} 

{%regroup interviews by company as company_list%}

<!-- TODO include all interview information -->
<!-- Group by date, eg. month ago, week ago, days ago -->

{%for company in company_list%}
    <h2>{{company.grouper}}</h2>
        {%regroup company.list by position as position_list%}
        <div class="indent">
        {%for position in position_list%}
            <h3>{{position.grouper}} position</h3>
            {%for interview in position.list%}
                <div class="interview">
                Date: {{interview.date}}<br>
                <p>
                <strong>Description:</strong><br>{{interview.description}}
                </p>
                {%ifnotequal interview.question_set.all.count 0%}
                    {%for question in interview.question_set.all%}
                        <div class="qAndA">
                        <strong>Question</strong><br>{{question.question}}</p>
                        {%if question.answer%}
                        <p><strong>Answer</strong><br>{{question.answer}}
                        {%endif%}
                        </div>
                    {%endfor%}
                {%endifnotequal%}
                {%if loggedin%}
                    {%ifequal profile interview.profile%}
                        <a href="/notes/edit/{{interview.id}}">edit</a>
                    {%endifequal%}
                {%endif%}
                </div>
            {%endfor%}
        {%endfor%}
        </div>
{%endfor%}

{%if not loggedin%}
<p>
Login to edit <a href="/login">here</a>.
</p>
{%endif%}
{%endblock content%}

templates/notes/position.html
{% extends "base.html" %}
{%block title%}{{position.title}}{%endblock%}
{%block header%}{{position.title}}{%endblock%}
{%block content%}

<p>
<h2>Companies</h2>
<ul>
{%for company in position.company_set.all%}
    <!-- TODO filter interview_set by position -->
    <li><a href="/notes/i/?company={{company.id}}&position={{position.id}}">{{company.name}}</a> - ({{company.interview_set.all.count}} interviews)
{%endfor%}
</ul>
</p>

<p>
<h2>Interviews</h2>
<ul>
{%for interview in position.interview_set.all%}
    <li>{{interview.description|truncatewords:10}}... - ({{interview.position.title}}) - {{interview.question_set.all.count}} questions - <a href="/notes/i/?position={{position.id}}">MORE</a></li>
{%endfor%}
</ul>
</p>

{%endblock content%}

templates/notes/position_index.html
{% extends "base.html" %}
{% load notes_extras %}
{%block title%}positions index{%endblock%}
{%block header%}Positions{%endblock%}
{%block content%}
Order by:
{%ifnotequal order "title"%}<a href="?order=title">{%endifnotequal%}
title
{%ifnotequal order "title"%}</a>{%endifnotequal%}
-
{%ifnotequal order "companies"%}<a href="?order=companies">{%endifnotequal%}
#companies
{%ifnotequal order "companies"%}</a>{%endifnotequal%}
-
{%ifnotequal order "interviews"%}<a href="?order=interviews">{%endifnotequal%}
#interviews
{%ifnotequal order "interviews"%}</a>{%endifnotequal%}
-
{%ifnotequal order "recent"%}<a href="?order=recent">{%endifnotequal%}
recent
{%ifnotequal order "recent"%}</a>{%endifnotequal%}

<ul>
{%for position in positions%}
    <li><a href="/notes/p/{{position.id}}">{{position.title}}</a> - ({{position.company_set.all.count}} companies, {{position.interview_set.all.count}} interviews) - updated {{position|format_updated}}
{%empty%}
    None
{%endfor%}
</ul>
{%endblock content%}

templates/notes/search.html
{%extends "base.html"%}
{%block title%}search{%endblock%}

{%block header%}NYI{%endblock%}

{%block content%}
Once we get enough content, we'll add search.  For now, just browse the index of companies and positions.
{%endblock content%}